[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = false
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200

[client]
showErrorDetails = true
toolbarMode = "minimal"

